# -*- coding: utf-8 -*-
"""Data visualization using Plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lj1Mlj4o3mUPEPC7GF7GS4sYtjcqyvO4
"""

!pip install plotly

import plotly

plotly.__version__

import pandas as pd
import seaborn as sns
from pandas.plotting import scatter_matrix
from matplotlib import pyplot as plotly
from matplotlib import font_manager as font_manager
from datetime import datetime, timedelta
import numpy as np
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go

#simple line plot
df = pd.DataFrame({"Years at work" : [1,2,3,4], "income": [6500,10000,12000,14000]})
df.head()

fig = px.line(df, x="Years at work", y="income", title="income by no. of years at work")
fig.show()

# Multiline plot with markers

stud = ['Rama', 'Shama', 'Bhama', 'Srini']
maths = [89,78,90,98]
science = [78,96,67,87]
programming = [81,87,92,99]
database_subject = [91, 93, 67, 89]

fig = go.Figure()
fig.add_trace(go.Scatter(x=stud, y=maths, name="Maths marks", line=dict(color="blue",width=4)))
fig.add_trace(go.Scatter(x=stud, y=science, name="Science marks", line=dict(color="red",width=4)))
fig.add_trace(go.Scatter(x=stud, y=programming, name="Programming marks", line=dict(color="green",width=4, dash='dash')))
fig.add_trace(go.Scatter(x=stud, y=database_subject, name="Database marks", line=dict(color="firebrick",width=4,dash='dash')))

fig.update_layout(title="Studensts Marks", xaxis_title="Student", yaxis_title="Marks")

fig.show()

#Bar plot
df = sns.load_dataset('titanic')
df.head()

fig = px.bar(df, x='pclass', y='fare', color='sex', title="Bar Plot for Passenger Class by Fare and Gender")
fig.show()

# Area Chart

fig =px.area(df, x='sex', y='age',color='survived', title="Area plot for Passenger status by gender and age")
fig.show()

#Stacked area chart
stud = ['Rama', 'Shama', 'Bama']
fig =go.Figure()
fig.add_trace(go.Scatter(x=stud, y=[40,10,20], hoverinfo='x+y', mode='lines', line=dict(width=0.6,color='rgb(172,89,200)'),
                         stackgroup='one'))
fig.add_trace(go.Scatter(x=stud, y=[50,5,2], hoverinfo='x+y', mode='lines', line=dict(width=0.6,color='rgb(100,51,190)'),
                         stackgroup='one'))

#Pie chart

stud = ['Rama', 'Shama','Bama', 'Srini', 'Arun', 'Sourav']
marks = [34,56,76,87,45,90,91]
fig = go.Figure(data=[go.Pie(labels=stud,values=marks,pull=[0,0,0,0.2,0,0])])
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.update_layout(title="Students and their marks")
fig.show()

fig =go.Figure(go.Sunburst(
    labels=["Ravi", "Vijay", "Arun", "Srini", "Rama", "Jileesh", "Sourav", "Abhishek", "Amith"],
    parents=["", "Ravi", "Ravi", "Arun", "Arun", "Ravi", "Ravi", "Sourav", "Ravi" ],
    values=[10, 14, 12, 10, 2, 6, 6, 4, 4],
))
# Update layout for tight margin
# See https://plotly.com/python/creating-and-updating-figures/
fig.update_layout(margin = dict(t=0, l=0, r=0, b=0))

fig.show()

#Scatter Plot

iris = sns.load_dataset('iris')
iris.head()

fig=px.scatter(iris, x="petal_length", y="petal_width", color="species", size='sepal_width', hover_data=['sepal_length'],
               title="Scatter plot of Iris Dataset")
fig.show()

